### ISSUE TITLE
Room Not Found

### ISSUE THREAD

**Issue by RenFinkle** [DyXel/Multirole#6]
Getting this error:
`System: Room not found, try refreshing the list `
when attempting to connect with edopro even when attempting to connect to an existing room created on the server via the "Host" functionality.
Build is latest as of 27 days ago
Build was done by building docker
Currently running the docker with default settings

**Comment by DyXel** [comment]
This usually happens when a room is made, the list of rooms is refreshed within the client and the room is closed by the Host before any other client has the chance to create a room that would take the id of the room that was just closed. Are you sure the client displaying that message does not fall within this category (very outdated room list, as it is updated only every 2 seconds)? if it does, then that is intended behavior and an easy way to avoid it is update the list in regular intervals manually. Otherwise, I need more information as at the moment i cannot reproduce by simply hosting a room and joining said room with a different client.

**Comment by RenFinkle** [comment]
Yup that was it ty.
